#!/usr/bin/env Rscript

######################
#    rCNV Project    #
######################

# Copyright (c) 2021-Present Ryan L. Collins and the Talkowski Laboratory
# Distributed under terms of the MIT License (see LICENSE)
# Contact: Ryan L. Collins <rlcollins@g.harvard.edu>

# Plot summary of global rCNV effects across HPOs


options(stringsAsFactors=F, scipen=1000)
require(rCNV2, quietly=T)


######################
### DATA FUNCTIONS ###
######################
# Load table of global meta-analysis stats
load.global.stats <- function(stats.in){
  stats <- read.table(stats.in, header=T, sep="\t", check.names=F, comment.char="")
  colnames(stats)[1] <- gsub("#", "", colnames(stats)[1], fixed=T)
  return(stats)
}

# Collect effect sizes for a single panel
get.effect.sizes <- function(stats, category, hpos, return.log2=TRUE){
  res <- lapply(hpos, function(hpo){
    if(hpo %in% stats$HPO){
      df <- as.data.frame(t(sapply(c("DUP", "CNV", "DEL"), function(cnv){
        as.numeric(stats[which(stats$HPO==hpo & stats$category==category & stats$CNV==cnv),
              c("meta_lnOR", "meta_lnOR_lower", "meta_lnOR_upper", "meta_neg_log10_p")])
      })))
    }else{
      df <- data.frame("meta_lnOR"=rep(NA, 3),
                       "meta_lnOR_lower"=rep(NA, 3),
                       "meta_lnOR_upper"=rep(NA, 3),
                       "meta_neg_log10_p"=rep(NA, 3),
                       row.names=c("DUP", "CNV", "DEL"))
    }
    df[, 1:3] <- apply(df[, 1:3], 1, exp)
    colnames(df) <- c("OR", "OR_lower", "OR_upper", "neg_log10_P")
    return(df)
  })
  if(return.log2){
    res <- lapply(res, function(df){
      df[, 1:3] <- apply(df[, 1:3], 1, log2)
      colnames(df)[1:3] <- paste("log2", colnames(df)[1:3], sep="_")
      return(df)
    })
  }
  names(res) <- hpos
  return(res)
}

# Get point formatting parameters for a single data frame generated by get.effect.sizes()
format.points <- function(df, bonf.p){
  bonf <- 10^-df[, "neg_log10_P"] <= bonf.p
  border <- control.cnv.colors[rownames(df)]
  border[which(bonf)] <- cnv.colors[rownames(df)][which(bonf)]
  fill <- cnv.whites[rownames(df)]
  fill[which(bonf)] <- cnv.colors[rownames(df)][which(bonf)]
  lwd <- rep(0.75, 3)
  lwd[which(bonf)] <- 1.25
  cex.adj <- rep(0.85, 3)
  cex.adj[which(bonf)] <- 1
  return(list("fill" = fill, "border" = border, "lwd" = lwd, "cex.adj" = cex.adj))
}


##########################
### PLOTTING FUNCTIONS ###
##########################
# Plot descriptive text columns
plot.text.columns <- function(hpos, meta, x.at=c(0, 2, 8), y.lab.buffer=0.05,
                              background=T, y.buffer=0.1, y.top=-0.6){
  # Get basic plotting info
  nhpos <- nrow(meta)
  y.at <- (1:nhpos)-0.5
  hpo.labels <- meta$HPO
  hpo.labels[which(hpo.labels == "UNKNOWN")] <- "N/A"

  # Prep plot area & add y-axis titles
  plot(x=NA, y=NA, xlim=c(0, 10), ylim=c(nhpos, y.top),
       xaxt="n", yaxt="n", xlab="", ylab="", xaxs="i", yaxs="i")
  sapply(1:length(x.at), function(i){
    axis(3, at=c(x.at[i]+0.125, (c(x.at[-1], par("usr")[2]) - 0.25)[i]),
         tck=0, labels=NA, xpd=T, col=blueblack, line=y.top)
  })
  height <- par("usr")[4]-par("usr")[3]
  text(x=x.at, y=par("usr")[4]+(y.lab.buffer*height)+(y.top*(sum(par("mar")[c(1,3)])/height)),
       labels=c("HPO", "Description", "Cases"),
       xpd=T, font=2, pos=4)

  # Plot text
  if(background==T){
    rect(xleft=par("usr")[1], xright=par("usr")[2],
         ybottom=y.at[which(!is.na(meta$HPO))]-0.5+y.buffer,
         ytop=y.at[which(!is.na(meta$HPO))]+0.5-y.buffer,
         border=NA, bty="n", col=bluewhite)
  }
  text(x=sapply(x.at, function(x){rep(x, nhpos)}), y=rep(y.at, 3),
       labels=c(hpo.labels, meta$description,
                sapply(meta$samples, function(x){if(is.na(x)){NA}else{prettyNum(x, big.mark=",")}})),
       pos=4, xpd=T)
}

# Plot a single panel of effect sizes
plot.ors <- function(stats, category, hpos, xlims=NULL, title=NULL,
                     ytop=-0.6, y.buffer=0.1, y.lab.buffer=0.015,
                     pt.cex=0.85, pt.vex=0.15){
  # Get plot data
  pdat <- get.effect.sizes(stats, category, hpos)
  if(is.null(xlims)){
    xlims <- range(unlist(sapply(pdat, function(x){x[, 1:3]})), na.rm=T)
  }
  xleft <- min(xlims); xright <- max(xlims)
  na.idxs <- which(sapply(hpos, is.na))

  # Prep plot area
  par(bty="n")
  plot(NA, xlim=xlims, ylim=c(length(hpos), ytop),
       xaxt="n", yaxt="n", xlab="", ylab="", xaxs="i", yaxs="i")
  rect(xleft=xleft, xright=xright, ybottom=length(pdat), ytop=0,
       border=NA, bty="n", col=bluewhite)
  rect(xleft=xleft, xright=xright,
       ybottom=c(0:(length(pdat)-1))+y.buffer,
       ytop=c(1:length(pdat))-y.buffer,
       border=NA, bty="n", col="white")
  segments(x0=0, x1=0, y0=0, y1=length(hpos), col=ns.color)
  if(length(na.idxs) > 0){
    rect(xleft=xleft, xright=xright, ybottom=na.idxs-1, ytop=na.idxs,
         border="white", bty="o", col="white")
  }
  rect(xleft=xleft, xright=xright,
       ybottom=c(0, na.idxs), ytop=c(na.idxs-1, length(hpos)),
       border=blueblack, col=NA, xpd=T)
  height <- par("usr")[4]-par("usr")[3]
  text(x=mean(par("usr")[1:2]), y=par("usr")[4]+(y.lab.buffer*height),
       labels=title, xpd=T, pos=3)

  # Add points
  point.ymods <- -0.5+c(-pt.vex, 0, pt.vex)
  sapply(1:length(pdat), function(y){
    df <- pdat[[y]]
    fmt <- format.points(df, bonf.p=0.05/nrow(stats))
    segments(x0=df[, 2], x1=df[, 3], y0=y+point.ymods, y1=y+point.ymods,
             lwd=fmt$lwd, col=fmt$border, lend="round")
    points(x=df[, 1], y=y+point.ymods, pch=21, cex=pt.cex*fmt$cex.adj,
           col=fmt$border, lwd=fmt$lwd, bg=fmt$fill)
  })

  # Add top Y-axis
  axis(3, at=-10:10, col=blueblack, tck=-0.025, labels=NA, line=ytop)
  sapply(-10:10, function(x){
    axis(3, at=x, tick=F, labels=2^x, line=ytop-0.5)
  })
}

# Wrapper to plot full table of rCNV effect sizes organized by HPO hierarchy
plot.global.effects.byhpo <- function(stats, meta, panel.widths,
                                y.top=-0.6, pt.cex=0.85,
                                parmar=c(0.2, 0.1, 4, 0.2)){
  # Subset stats to HPOs in meta
  stats <- stats[which(stats$HPO %in% meta$HPO), ]
  hpos <- meta$HPO

  # Prep layout
  layout(matrix(c(1:length(panel.widths)), nrow=1, byrow=T), widths=panel.widths)
  par(bty="n", mar=parmar)

  # Plot dendrogram in left margin
  plot.dendro(meta, color=blueblack, lwd=2, box.wex=1.5, y.top=y.top)

  # Add text labels
  plot.text.columns(hpos, meta, x.at=c(0, 1.7, 8.75),
                    y.top=y.top, y.lab.buffer=0.0025)

  # Get effect size limits
  or.lims <- 1.1 * range(log2(exp(stats$meta_lnOR)))

  # Category 2: All Genic rCNVs
  plot.ors(stats, 2, meta$HPO, xlims=or.lims, ytop=y.top, pt.cex=pt.cex,
           title="Any Gene")

  # Category 3: Known GDs
  plot.ors(stats, 3, meta$HPO, xlims=or.lims, ytop=y.top, pt.cex=pt.cex,
           title="Established\nGenomic Disorders (GDs)")

  # Category 5: Known DS genes outside of GDs
  plot.ors(stats, 5, meta$HPO, xlims=or.lims, ytop=y.top, pt.cex=pt.cex,
           title="Dosage Sensitive (DS) Genes\n(Excluding GDs)")

  # Category 7: constrained genes genes outside of known GDs & DS genes
  plot.ors(stats, 7, meta$HPO, xlims=or.lims, ytop=y.top, pt.cex=pt.cex,
           title="LoF-Constrained Genes\n(Exclud. GDs + DS Genes)")

  # Category 8: all remaining genes
  plot.ors(stats, 8, meta$HPO, xlims=or.lims, ytop=y.top, pt.cex=pt.cex,
           title="All Other Genes\n(Excl. GDs, DS, and Constr.)")
}


#####################
### RSCRIPT BLOCK ###
#####################
require(optparse, quietly=T)

# List of command-line options
option_list <- list()

# Get command-line arguments & options
args <- parse_args(OptionParser(usage=paste("%prog hpos.txt metadata.tsv counts.tsv stats.tsv out_prefix", sep=" "),
                                option_list=option_list),
                   positional_arguments=TRUE)
opts <- args$options

# Checks for appropriate positional arguments
if(length(args$args) != 5){
  stop(paste("Five positional arguments required: hpos.txt, metadata.tsv, counts.tsv, stats.tsv, out_prefix\n", sep=" "))
}

# Writes args & opts to vars
hpos.in <- args$args[1]
meta.in <- args$args[2]
sample.counts.in <- args$args[3]
stats.in <- args$args[4]
out.prefix <- args$args[5]

# # DEV PARAMETERS
# hpos.in <- "~/scratch/rCNV2_analysis_d2.reordered_hpos.txt"
# meta.in <- "~/scratch/phenotype_groups.HPO_metadata.txt"
# sample.counts.in <- "~/scratch/HPOs_by_metacohort.table.tsv"
# stats.in <- "~/scratch/rCNV2_analysis_d2.global_burden_stats.tsv.gz"
# out.prefix <- "~/scratch/test"

# Read data
hpos <- as.character(read.table(hpos.in, header=F, sep="\t")[, 1])
meta <- load.hpo.metadata(meta.in, sample.counts.in, hpos)
stats <- load.global.stats(stats.in)

# Plot figure
panel.widths <- c(1.1, 10, rep(3.5, 5))
pdf(paste(out.prefix, "pdf", sep="."), height=7.75, width=12)
plot.global.effects.byhpo(stats, meta, panel.widths,
                    parmar=c(0.2, 0.1, 3, 0.2))
dev.off()




