#!/usr/bin/env Rscript

######################
#    rCNV Project    #
######################

# Copyright (c) 2020 Ryan L. Collins and the Talkowski Laboratory
# Distributed under terms of the MIT License (see LICENSE)
# Contact: Ryan L. Collins <rlcollins@g.harvard.edu>

# Plot distributions of primary & secondary p-values from sliding window meta analysis

# DEV NOTE: this code snippet is mostly saved for convenience, and references paths
#           to local files on RLC's computer that were generated by sliding_window_analysis.sh


options(scipen=1000, stringsAsFactors=F)


# Plot histogram of observed primary p-values from rCNV sliding window meta-analysis

x <- read.table("~/scratch/rCNV.observed_pval_matrix.txt.gz", header=T, sep="\t")
x <- t(apply(x, 1, function(x){10^-as.numeric(x)}))

pdf("~/scratch/rCNV.observed_pval_distribution.sliding_window_meta_analysis.pdf",
    height=5, width=8)
hist(x[which(x<1)], breaks=200, col="gray20", freq=F,
     xlab="Meta-analysis P-value", 
     main=paste("Distribution of meta-analysis P-values",
                "across all phenotypes, windows, and CNV classes",
                sep="\n"))
mtext(3, line=-1.5, text=paste("Note: windows with P=1 not shown (i.e., where zero case CNVs are observed).", 
                               "These comprise the majority of all windows.", sep="\n"),
      font=3, cex=0.85)
dev.off()


# Plot histogram of observed secondary p-values from rCNV sliding window meta-analysis

s <- read.table("~/scratch/rCNV.observed_pval_matrix_secondary.txt.gz", header=T, sep="\t")
s <- t(apply(s, 1, function(s){10^-as.numeric(s)}))

pdf("~/scratch/rCNV.observed_secondary_pval_distribution.sliding_window_meta_analysis.pdf",
    height=5, width=8)
hist(s[which(s<1)], breaks=200, col="gray20", freq=F,
     xlab="Secondary meta-analysis P-value", 
     main=paste("Distribution of secondary meta-analysis P-values",
                "across all phenotypes, windows, and CNV classes",
                sep="\n"))
mtext(3, line=-1.5, text=paste("Note: windows with P=1 not shown (i.e., where zero case CNVs are observed).", 
                               "These comprise the majority of all windows.", sep="\n"),
      font=3, cex=0.85)
dev.off()


# Scatterplot of all primary vs secondary P-values

pairs <- data.frame("p"=as.vector(unlist(x)),
                    "s"=as.vector(unlist(s)))
pairs$p[which(is.na(pairs$p))] <- 1
pairs$s[which(is.na(pairs$s))] <- 1
pairs <- pairs[-which(pairs$p>=0.05 & pairs$s>=0.05), ]
sig.pairs.idx <- which(-log10(pairs$p)>6 & pairs$s<0.05)

png("~/scratch/rCNV.primary_vs_secondary_pvalues.png", height=300*5, width=300*5, res=300)
plot(-log10(pairs$p), -log10(pairs$s), cex=0.2,
     panel.first=c(abline(0, 1, lty=2, col="gray50")),
     xlim=c(0, 40), ylim=c(0, 40),
     xlab="-log10(P) Primary", ylab="-log10(P) Secondary",
     main="Primary vs. Secondary P-Values\nAll phenotypes & all CNV types")
points(-log10(pairs$p)[sig.pairs.idx], -log10(pairs$s)[sig.pairs.idx], 
       pch=19, cex=0.2, col="red")
rect(xleft=0, xright=-log10(0.05), ybottom=0, ytop=-log10(0.05), col="black")
dev.off()


# Scatterplot of primary vs secondary P-values for genomic disorders only

bins <- read.table("~/scratch/rCNV.sliding_window.meta_analysis.bins.bed.gz",
                   header=T, sep="\t", comment.char="")
colnames(bins)[1] <- "chr"

GDs <- read.table("~/Desktop/Collins/Talkowski/CNV_DB/rCNV_map/rCNV2/refs/UKBB_GD.Owen_2018.bed.gz",
                  header=T, sep="\t", comment.char="")
colnames(GDs)[1] <- "chr"

bin.gd.idxs <- which(sapply(1:nrow(bins), function(i){
  any(bins$chr[i] == GDs$chr & bins$start[i] >= GDs$start & bins$end[i] <= GDs$end)
}))


gd.pairs <- data.frame("p"=as.vector(unlist(x[bin.gd.idxs, ])),
                       "s"=as.vector(unlist(s[bin.gd.idxs, ])))
gd.pairs$p[which(is.na(gd.pairs$p))] <- 1
gd.pairs$s[which(is.na(gd.pairs$s))] <- 1
# gd.pairs <- gd.pairs[-which(gd.pairs$p>=0.05 & gd.pairs$s>=0.05), ]
sig.gd.pairs.idx <- which(-log10(gd.pairs$p)>6 & gd.pairs$s<0.05)
fn.gd.pairs.idx <- which(-log10(gd.pairs$p)>6 & gd.pairs$s>=0.05)

png("~/scratch/rCNV.primary_vs_secondary_pvalues.gds_only.png", height=300*5, width=300*5, res=300)
plot(-log10(gd.pairs$p), -log10(gd.pairs$s), cex=0.2,
     panel.first=c(abline(0, 1, lty=2, col="gray50")),
     xlim=c(0, 20), ylim=c(0, 20),
     xlab="-log10(P) Primary", ylab="-log10(P) Secondary",
     main="Primary vs. Secondary P-Values\nKnown Genomic Disorders Only")
points(-log10(gd.pairs$p)[sig.gd.pairs.idx], -log10(gd.pairs$s)[sig.gd.pairs.idx], 
       pch=19, cex=0.2, col="red")
points(-log10(gd.pairs$p)[fn.gd.pairs.idx], -log10(gd.pairs$s)[fn.gd.pairs.idx], 
       pch=19, cex=0.2, col="blue")
legend("topleft", col=c("black", "red", "blue"), pch=19,
       legend=c("Not significant", "True positive", "False negative"))
dev.off()


